# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: antispam/playintegrity/v1/playintegrity_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import kik_unofficial.protobuf.protobuf_validation_pb2
import kik_unofficial.protobuf.antispam.playintegrity.v1.playintegrity_service_pb2


class PlayIntegrityBase(abc.ABC):

    @abc.abstractmethod
    async def GetNonce(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceRequest, kik_unofficial.protobuf.antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def VerifyAttestationResult(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultRequest, kik_unofficial.protobuf.antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/mobile.antispam.playintegrity.v1.PlayIntegrity/GetNonce': grpclib.const.Handler(
                self.GetNonce,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceRequest,
kik_unofficial.protobuf.                antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceResponse,
            ),
            '/mobile.antispam.playintegrity.v1.PlayIntegrity/VerifyAttestationResult': grpclib.const.Handler(
                self.VerifyAttestationResult,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultRequest,
kik_unofficial.protobuf.                antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultResponse,
            ),
        }


class PlayIntegrityStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetNonce = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.antispam.playintegrity.v1.PlayIntegrity/GetNonce',
kik_unofficial.protobuf.            antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceRequest,
kik_unofficial.protobuf.            antispam.playintegrity.v1.playintegrity_service_pb2.GetNonceResponse,
        )
        self.VerifyAttestationResult = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.antispam.playintegrity.v1.PlayIntegrity/VerifyAttestationResult',
kik_unofficial.protobuf.            antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultRequest,
kik_unofficial.protobuf.            antispam.playintegrity.v1.playintegrity_service_pb2.VerifyAttestationResultResponse,
        )
