# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antispam/playintegrity/v1/playintegrity_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5antispam/playintegrity/v1/playintegrity_service.proto\x12 mobile.antispam.playintegrity.v1\x1a\x19protobuf_validation.proto\"\x11\n\x0fGetNonceRequest\"\x88\x01\n\x10GetNonceResponse\x12I\n\x06result\x18\x01 \x01(\x0e\x32\x39.mobile.antispam.playintegrity.v1.GetNonceResponse.Result\x12\x17\n\x05nonce\x18\x02 \x01(\tB\x08\xca\x9d%\x04\x08\x01(\x10\"\x10\n\x06Result\x12\x06\n\x02OK\x10\x00\";\n\x1eVerifyAttestationResultRequest\x12\x19\n\x03jws\x18\x01 \x01(\tB\x0c\xca\x9d%\x08\x08\x01(\x01\x30\xa8\xc3\x01\"\xb7\x01\n\x1fVerifyAttestationResultResponse\x12X\n\x06result\x18\x01 \x01(\x0e\x32H.mobile.antispam.playintegrity.v1.VerifyAttestationResultResponse.Result\":\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_NONCE\x10\x01\x12\x15\n\x11MALFORMED_REQUEST\x10\x02\x32\xa7\x02\n\rPlayIntegrity\x12s\n\x08GetNonce\x12\x31.mobile.antispam.playintegrity.v1.GetNonceRequest\x1a\x32.mobile.antispam.playintegrity.v1.GetNonceResponse\"\x00\x12\xa0\x01\n\x17VerifyAttestationResult\x12@.mobile.antispam.playintegrity.v1.VerifyAttestationResultRequest\x1a\x41.mobile.antispam.playintegrity.v1.VerifyAttestationResultResponse\"\x00\x42\x87\x01\n\"com.kik.antispam.playintegrity.rpcZagithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/playintegrity/v1;playintegrityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antispam.playintegrity.v1.playintegrity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.kik.antispam.playintegrity.rpcZagithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/playintegrity/v1;playintegrity'
  _globals['_GETNONCERESPONSE'].fields_by_name['nonce']._loaded_options = None
  _globals['_GETNONCERESPONSE'].fields_by_name['nonce']._serialized_options = b'\312\235%\004\010\001(\020'
  _globals['_VERIFYATTESTATIONRESULTREQUEST'].fields_by_name['jws']._loaded_options = None
  _globals['_VERIFYATTESTATIONRESULTREQUEST'].fields_by_name['jws']._serialized_options = b'\312\235%\010\010\001(\0010\250\303\001'
  _globals['_GETNONCEREQUEST']._serialized_start=118
  _globals['_GETNONCEREQUEST']._serialized_end=135
  _globals['_GETNONCERESPONSE']._serialized_start=138
  _globals['_GETNONCERESPONSE']._serialized_end=274
  _globals['_GETNONCERESPONSE_RESULT']._serialized_start=258
  _globals['_GETNONCERESPONSE_RESULT']._serialized_end=274
  _globals['_VERIFYATTESTATIONRESULTREQUEST']._serialized_start=276
  _globals['_VERIFYATTESTATIONRESULTREQUEST']._serialized_end=335
  _globals['_VERIFYATTESTATIONRESULTRESPONSE']._serialized_start=338
  _globals['_VERIFYATTESTATIONRESULTRESPONSE']._serialized_end=521
  _globals['_VERIFYATTESTATIONRESULTRESPONSE_RESULT']._serialized_start=463
  _globals['_VERIFYATTESTATIONRESULTRESPONSE_RESULT']._serialized_end=521
  _globals['_PLAYINTEGRITY']._serialized_start=524
  _globals['_PLAYINTEGRITY']._serialized_end=819
# @@protoc_insertion_point(module_scope)
