# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups/v1/group_suggest_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%groups/v1/group_suggest_service.proto\x12\x10mobile.groups.v1\x1a\x19protobuf_validation.proto\"%\n#GetSuggestedGroupSearchTermsRequest\"\xc7\x02\n$GetSuggestedGroupSearchTermsResponse\x12M\n\x06result\x18\x01 \x01(\x0e\x32=.mobile.groups.v1.GetSuggestedGroupSearchTermsResponse.Result\x12g\n\x0esuggested_term\x18\x02 \x03(\x0b\x32\x44.mobile.groups.v1.GetSuggestedGroupSearchTermsResponse.SuggestedTermB\t\xca\x9d%\x05\x08\x00\x80\x01\x64\x1a<\n\rSuggestedTerm\x12+\n\x04term\x18\x01 \x01(\tB\x1d\xca\x9d%\x19\x08\x01\x12\x15^[A-Za-z0-9._]{1,32}$\")\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13RATE_LIMIT_EXCEEDED\x10\x01\x32\xa0\x01\n\x0cGroupSuggest\x12\x8f\x01\n\x1cGetSuggestedGroupSearchTerms\x12\x35.mobile.groups.v1.GetSuggestedGroupSearchTermsRequest\x1a\x36.mobile.groups.v1.GetSuggestedGroupSearchTermsResponse\"\x00\x42\\\n\x0e\x63om.kik.groupsZJgithub.com/kikinteractive/xiphias-api-mobile/generated/go/groups/v1;groupsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups.v1.group_suggest_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.kik.groupsZJgithub.com/kikinteractive/xiphias-api-mobile/generated/go/groups/v1;groups'
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_SUGGESTEDTERM'].fields_by_name['term']._loaded_options = None
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_SUGGESTEDTERM'].fields_by_name['term']._serialized_options = b'\312\235%\031\010\001\022\025^[A-Za-z0-9._]{1,32}$'
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE'].fields_by_name['suggested_term']._loaded_options = None
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE'].fields_by_name['suggested_term']._serialized_options = b'\312\235%\005\010\000\200\001d'
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSREQUEST']._serialized_start=86
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSREQUEST']._serialized_end=123
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE']._serialized_start=126
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE']._serialized_end=453
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_SUGGESTEDTERM']._serialized_start=350
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_SUGGESTEDTERM']._serialized_end=410
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_RESULT']._serialized_start=412
  _globals['_GETSUGGESTEDGROUPSEARCHTERMSRESPONSE_RESULT']._serialized_end=453
  _globals['_GROUPSUGGEST']._serialized_start=456
  _globals['_GROUPSUGGEST']._serialized_end=616
# @@protoc_insertion_point(module_scope)
