# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/chat_theme.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.entity.v1 import element_common_pb2 as entity_dot_v1_dot_element__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessagepath/v1/chat_theme.proto\x12\x15\x63ommon.messagepath.v1\x1a\x19protobuf_validation.proto\x1a\x1e\x65ntity/v1/element_common.proto\"\x96\x01\n\x13\x43hatThemeAttachment\x12:\n\x0enew_chat_theme\x18\x01 \x01(\x0b\x32\".common.entity.v1.ChatThemeElement\x12\x43\n\x13new_chat_theme_lock\x18\x02 \x01(\x0b\x32&.common.entity.v1.ChatThemeLockElementBy\n\x19\x63om.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\xa2\x02\x03KPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagepath.v1.chat_theme_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\003KPB'
  _globals['_CHATTHEMEATTACHMENT']._serialized_start=118
  _globals['_CHATTHEMEATTACHMENT']._serialized_end=268
# @@protoc_insertion_point(module_scope)
