# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/link_message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.messagepath.v1 import core_message_common_pb2 as messagepath_dot_v1_dot_core__message__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!messagepath/v1/link_message.proto\x12\x15\x63ommon.messagepath.v1\x1a\x19protobuf_validation.proto\x1a(messagepath/v1/core_message_common.proto\"\xdb\x02\n\x15LinkMessageAttachment\x12<\n\x04uris\x18\x01 \x03(\x0b\x32!.common.messagepath.v1.UriElementB\x0b\xca\x9d%\x07\x08\x01x\x01\x80\x01\n\x12\x16\n\x05title\x18\x32 \x01(\tB\x07\xca\x9d%\x03\x30\xe8\x07\x12\x15\n\x04text\x18\x33 \x01(\tB\x07\xca\x9d%\x03\x30\xd0\x0f\x12\x36\n\x07picture\x18\x34 \x01(\x0b\x32%.common.messagepath.v1.PictureElement\x12\x41\n\x0b\x61ttribution\x18\x35 \x01(\x0b\x32,.common.messagepath.v1.AttributionAttachment\x12\x43\n\x0e\x63ontent_layout\x18\x36 \x01(\x0b\x32+.common.messagepath.v1.ContentLayoutElement\x12\x15\n\rallow_forward\x18\x37 \x01(\x08\x42z\n\x19\x63om.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\xa2\x02\x04MPTHb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagepath.v1.link_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\004MPTH'
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['uris']._loaded_options = None
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['uris']._serialized_options = b'\312\235%\007\010\001x\001\200\001\n'
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['title']._loaded_options = None
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['title']._serialized_options = b'\312\235%\0030\350\007'
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['text']._loaded_options = None
  _globals['_LINKMESSAGEATTACHMENT'].fields_by_name['text']._serialized_options = b'\312\235%\0030\320\017'
  _globals['_LINKMESSAGEATTACHMENT']._serialized_start=130
  _globals['_LINKMESSAGEATTACHMENT']._serialized_end=477
# @@protoc_insertion_point(module_scope)
