# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/text_markdown.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"messagepath/v1/text_markdown.proto\x12\x15\x63ommon.messagepath.v1\x1a\x19protobuf_validation.proto\"3\n\x16TextMarkdownAttachment\x12\x19\n\x08markdown\x18\x01 \x01(\tB\x07\xca\x9d%\x03\x30\xc4\x13\x42z\n\x19\x63om.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\xa2\x02\x04MPTHb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagepath.v1.text_markdown_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\004MPTH'
  _globals['_TEXTMARKDOWNATTACHMENT'].fields_by_name['markdown']._loaded_options = None
  _globals['_TEXTMARKDOWNATTACHMENT'].fields_by_name['markdown']._serialized_options = b'\312\235%\0030\304\023'
  _globals['_TEXTMARKDOWNATTACHMENT']._serialized_start=88
  _globals['_TEXTMARKDOWNATTACHMENT']._serialized_end=139
# @@protoc_insertion_point(module_scope)
