# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/widgets.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.messagepath.v1 import keyboards_pb2 as messagepath_dot_v1_dot_keyboards__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmessagepath/v1/widgets.proto\x12\x15\x63ommon.messagepath.v1\x1a\x12\x63ommon_model.proto\x1a\x19protobuf_validation.proto\x1a\x1emessagepath/v1/keyboards.proto\"P\n\x10WidgetAttachment\x12<\n\x07widgets\x18\x01 \x03(\x0b\x32\x1d.common.messagepath.v1.WidgetB\x0c\xca\x9d%\x08\x08\x01x\x01\x80\x01\xe8\x07\"u\n\x06Widget\x12)\n\x02to\x18\x01 \x01(\x0b\x32\x15.common.XiBareUserJidB\x06\xca\x9d%\x02\x08\x00\x12\x38\n\x0btext_widget\x18  \x01(\x0b\x32!.common.messagepath.v1.TextWidgetH\x00\x42\x06\n\x04type\"|\n\nTextWidget\x12\x19\n\x04\x62ody\x18\x01 \x01(\tB\x0b\xca\x9d%\x07\x08\x01(\x01\x30\xe8\x07\x12\x18\n\x05title\x18\x02 \x01(\tB\t\xca\x9d%\x05\x08\x00\x30\xe8\x07\x12\x39\n\x08keyboard\x18\x03 \x01(\x0b\x32\x1f.common.messagepath.v1.KeyboardB\x06\xca\x9d%\x02\x08\x00\x42z\n\x19\x63om.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\xa2\x02\x04MPTHb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagepath.v1.widgets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\004MPTH'
  _globals['_WIDGETATTACHMENT'].fields_by_name['widgets']._loaded_options = None
  _globals['_WIDGETATTACHMENT'].fields_by_name['widgets']._serialized_options = b'\312\235%\010\010\001x\001\200\001\350\007'
  _globals['_WIDGET'].fields_by_name['to']._loaded_options = None
  _globals['_WIDGET'].fields_by_name['to']._serialized_options = b'\312\235%\002\010\000'
  _globals['_TEXTWIDGET'].fields_by_name['body']._loaded_options = None
  _globals['_TEXTWIDGET'].fields_by_name['body']._serialized_options = b'\312\235%\007\010\001(\0010\350\007'
  _globals['_TEXTWIDGET'].fields_by_name['title']._loaded_options = None
  _globals['_TEXTWIDGET'].fields_by_name['title']._serialized_options = b'\312\235%\005\010\0000\350\007'
  _globals['_TEXTWIDGET'].fields_by_name['keyboard']._loaded_options = None
  _globals['_TEXTWIDGET'].fields_by_name['keyboard']._serialized_options = b'\312\235%\002\010\000'
  _globals['_WIDGETATTACHMENT']._serialized_start=134
  _globals['_WIDGETATTACHMENT']._serialized_end=214
  _globals['_WIDGET']._serialized_start=216
  _globals['_WIDGET']._serialized_end=333
  _globals['_TEXTWIDGET']._serialized_start=335
  _globals['_TEXTWIDGET']._serialized_end=459
# @@protoc_insertion_point(module_scope)
