# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masks/v1/masksdata_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n masks/v1/masksdata_service.proto\x12\x0fmobile.masks.v1\x1a\x19protobuf_validation.proto\"[\n\x0bListRequest\x12\'\n\x16requested_list_version\x18\x01 \x01(\tB\x07\xca\x9d%\x03\x30\xa3\x10\x12#\n\x12local_list_version\x18\x02 \x01(\tB\x07\xca\x9d%\x03\x30\xa3\x10\"f\n\x0cListResponse\x12\x17\n\x07version\x18\x01 \x01(\tB\x06\xca\x9d%\x02\x08\x01\x12=\n\tresources\x18\x02 \x03(\x0b\x32\x1c.mobile.masks.v1.MaskDetailsB\x0c\xca\x9d%\x08\x08\x01x\x01\x80\x01\xc8\x01\"\xad\x03\n\x0bMaskDetails\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xca\x9d%\x02\x08\x01\x12\x14\n\x04name\x18\x02 \x01(\tB\x06\xca\x9d%\x02\x08\x01\x12\"\n\rthumbnail_url\x18\x03 \x01(\tB\x0b\xca\x9d%\x07\x08\x01(\x01\x30\xa3\x10\x12\x1b\n\x0b\x66rame_count\x18\x04 \x01(\rB\x06\xca\x9d%\x02\x08\x01\x12\x1a\n\nframe_rate\x18\x05 \x01(\rB\x06\xca\x9d%\x02\x08\x01\x12\x1a\n\nloop_count\x18\x06 \x01(\rB\x06\xca\x9d%\x02\x08\x01\x12.\n\x19sequence_archive_location\x18\x07 \x01(\tB\x0b\xca\x9d%\x07\x08\x01(\x01\x30\xa3\x10\x12!\n\x0esequence_order\x18\x08 \x03(\x05\x42\t\xca\x9d%\x05x\x00\x80\x01\x64\x12\x41\n\trectangle\x18\t \x01(\x0b\x32&.mobile.masks.v1.MaskDetails.RectangleB\x06\xca\x9d%\x02\x08\x01\x1a\x65\n\tRectangle\x12\x13\n\x03top\x18\x01 \x01(\x05\x42\x06\xca\x9d%\x02\x08\x01\x12\x14\n\x04left\x18\x02 \x01(\x05\x42\x06\xca\x9d%\x02\x08\x01\x12\x15\n\x05width\x18\x03 \x01(\x05\x42\x06\xca\x9d%\x02\x08\x01\x12\x16\n\x06height\x18\x04 \x01(\x05\x42\x06\xca\x9d%\x02\x08\x01\x32\xf9\x01\n\tMasksData\x12P\n\x11GetProductionList\x12\x1c.mobile.masks.v1.ListRequest\x1a\x1d.mobile.masks.v1.ListResponse\x12K\n\x0cGetStageList\x12\x1c.mobile.masks.v1.ListRequest\x1a\x1d.mobile.masks.v1.ListResponse\x12M\n\x0eGetVersionList\x12\x1c.mobile.masks.v1.ListRequest\x1a\x1d.mobile.masks.v1.ListResponseBe\n\x15\x63om.kik.masksdata.rpcZLgithub.com/kikinteractive/xiphias-api-mobile/generated/go/masks/v1;masksdatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'masks.v1.masksdata_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.kik.masksdata.rpcZLgithub.com/kikinteractive/xiphias-api-mobile/generated/go/masks/v1;masksdata'
  _globals['_LISTREQUEST'].fields_by_name['requested_list_version']._loaded_options = None
  _globals['_LISTREQUEST'].fields_by_name['requested_list_version']._serialized_options = b'\312\235%\0030\243\020'
  _globals['_LISTREQUEST'].fields_by_name['local_list_version']._loaded_options = None
  _globals['_LISTREQUEST'].fields_by_name['local_list_version']._serialized_options = b'\312\235%\0030\243\020'
  _globals['_LISTRESPONSE'].fields_by_name['version']._loaded_options = None
  _globals['_LISTRESPONSE'].fields_by_name['version']._serialized_options = b'\312\235%\002\010\001'
  _globals['_LISTRESPONSE'].fields_by_name['resources']._loaded_options = None
  _globals['_LISTRESPONSE'].fields_by_name['resources']._serialized_options = b'\312\235%\010\010\001x\001\200\001\310\001'
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['top']._loaded_options = None
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['top']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['left']._loaded_options = None
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['left']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['width']._loaded_options = None
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['width']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['height']._loaded_options = None
  _globals['_MASKDETAILS_RECTANGLE'].fields_by_name['height']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['id']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['name']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['name']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['thumbnail_url']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['thumbnail_url']._serialized_options = b'\312\235%\007\010\001(\0010\243\020'
  _globals['_MASKDETAILS'].fields_by_name['frame_count']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['frame_count']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['frame_rate']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['frame_rate']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['loop_count']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['loop_count']._serialized_options = b'\312\235%\002\010\001'
  _globals['_MASKDETAILS'].fields_by_name['sequence_archive_location']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['sequence_archive_location']._serialized_options = b'\312\235%\007\010\001(\0010\243\020'
  _globals['_MASKDETAILS'].fields_by_name['sequence_order']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['sequence_order']._serialized_options = b'\312\235%\005x\000\200\001d'
  _globals['_MASKDETAILS'].fields_by_name['rectangle']._loaded_options = None
  _globals['_MASKDETAILS'].fields_by_name['rectangle']._serialized_options = b'\312\235%\002\010\001'
  _globals['_LISTREQUEST']._serialized_start=80
  _globals['_LISTREQUEST']._serialized_end=171
  _globals['_LISTRESPONSE']._serialized_start=173
  _globals['_LISTRESPONSE']._serialized_end=275
  _globals['_MASKDETAILS']._serialized_start=278
  _globals['_MASKDETAILS']._serialized_end=707
  _globals['_MASKDETAILS_RECTANGLE']._serialized_start=606
  _globals['_MASKDETAILS_RECTANGLE']._serialized_end=707
  _globals['_MASKSDATA']._serialized_start=710
  _globals['_MASKSDATA']._serialized_end=959
# @@protoc_insertion_point(module_scope)
