syntax = "proto3";

package mobile.login.jwt.v1;

option java_package = "com.kik.login.jwt.rpc";
option go_package = "github.com/kikinteractive/xiphias-api-mobile/generated/go/login/jwt/v1;jwt";

import "protobuf_validation.proto";
import "common_model.proto";
import "login/v1/mobile_login_service.proto";

service MobileLoginJwt {
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
}

message RefreshTokenRequest {
  oneof CredentialsType {
    mobile.login.v1.UsernameCredentials username_creds = 1;
  }

  common.XiDeviceId device_id = 2 [(kik.validation.field_validation) = {
    mandatory: true
  }];

  common.XiLocale locale = 3 [(kik.validation.field_validation) = {
    mandatory: true
  }];

  common.XiClientVersion version = 4 [(kik.validation.field_validation) = {
    mandatory: true
  }];

  oneof MiscDeviceInfo {
    mobile.login.v1.AndroidInfo android_info = 5;
    mobile.login.v1.IosInfo ios_info = 6;
  }

  // Play Integrity Token
  string integrity_token = 7 [(kik.validation.field_validation) = {
    mandatory: false
  }];

  // reCAPTCHA Mobile Token
  // Action: 'jwt_refresh'
  //
  // Site key (Android): `6LdKmiUpAAAAAHFBRsgyjg7Sy2saQwLtNV_JZ-56`
  // Package Name (Android): `kik.android`
  //
  // Site key (iOS): `6Ld88CYpAAAAAPOMcxVQ7haXoeJpNewmJ25UMAb-`
  // iOS Bundle ID (iOS): `com.kik.chat`
  string recaptcha_token = 8 [(kik.validation.field_validation) = {
    mandatory: false
  }];
  string apple_device_check_token = 9 [(kik.validation.field_validation) = {
    mandatory: false
  }];
  string apple_device_check_key_id = 10 [(kik.validation.field_validation) = {
    mandatory: false
  }];
  string apple_assertion = 11 [(kik.validation.field_validation) = {
    mandatory: false
  }];
  string refresh_token = 12 [(kik.validation.field_validation) = {
    mandatory: false
    min_byte_length: 1
    max_byte_length: 15000 // sanity bound
  }];
}

message RefreshTokenResponse {
  Result result = 1;

  // Available on OK result.
  string refresh_token = 2;
  string access_token = 3;

  // Available on INVALID/ERROR on debug
  string reason = 4;

  string message = 5;
}

enum Result {
  OK = 0;
  SERVER_ERROR = 1;

  // Invalid password or rate limited
  CLIENT_ERROR = 2;

  SERVICE_UNAVAILABLE = 3;
  TOKEN_ERROR = 4;
  VERIFY = 5;

  // Request rejected for anti spam reasons
  VERIFICATION_FAILED = 6;
}