# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: login/v1/mobile_login_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import kik_unofficial.protobuf.protobuf_validation_pb2
import kik_unofficial.protobuf.common_model_pb2
import kik_unofficial.protobuf.login.v1.mobile_login_service_pb2


class MobileLoginBase(abc.ABC):

    @abc.abstractmethod
    async def Login(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.login.v1.mobile_login_service_pb2.LoginRequest, kik_unofficial.protobuf.login.v1.mobile_login_service_pb2.LoginResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Register(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.login.v1.mobile_login_service_pb2.RegisterRequest, kik_unofficial.protobuf.login.v1.mobile_login_service_pb2.RegisterResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/mobile.login.v1.MobileLogin/Login': grpclib.const.Handler(
                self.Login,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                login.v1.mobile_login_service_pb2.LoginRequest,
kik_unofficial.protobuf.                login.v1.mobile_login_service_pb2.LoginResponse,
            ),
            '/mobile.login.v1.MobileLogin/Register': grpclib.const.Handler(
                self.Register,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                login.v1.mobile_login_service_pb2.RegisterRequest,
kik_unofficial.protobuf.                login.v1.mobile_login_service_pb2.RegisterResponse,
            ),
        }


class MobileLoginStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Login = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.login.v1.MobileLogin/Login',
kik_unofficial.protobuf.            login.v1.mobile_login_service_pb2.LoginRequest,
kik_unofficial.protobuf.            login.v1.mobile_login_service_pb2.LoginResponse,
        )
        self.Register = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.login.v1.MobileLogin/Register',
kik_unofficial.protobuf.            login.v1.mobile_login_service_pb2.RegisterRequest,
kik_unofficial.protobuf.            login.v1.mobile_login_service_pb2.RegisterResponse,
        )
