# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kik_options.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11kik_options.proto\x12\x03kik\x1a google/protobuf/descriptor.proto\"t\n\x11\x43heckStyleOptions\x12\x1a\n\x0bignore_path\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x0eignore_version\x18\x02 \x01(\x08:\x05\x66\x61lse\x12$\n\x15ignore_package_prefix\x18\x03 \x01(\x08:\x05\x66\x61lse:J\n\ncheckstyle\x12\x1c.google.protobuf.FileOptions\x18\xb5\xa4\x05 \x01(\x0b\x32\x16.kik.CheckStyleOptionsBd\n\x0f\x63om.kik.optionsZQgithub.com/kikinteractive/xiphias-model-common/generated/go/kikoptions;kikoptions')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kik_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.kik.optionsZQgithub.com/kikinteractive/xiphias-model-common/generated/go/kikoptions;kikoptions'
  _globals['_CHECKSTYLEOPTIONS']._serialized_start=60
  _globals['_CHECKSTYLEOPTIONS']._serialized_end=176
# @@protoc_insertion_point(module_scope)
