# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile_video_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
import kik_unofficial.protobuf.common_rpc_pb2 as common__rpc__pb2
from kik_unofficial.protobuf.video.v1 import video_common_pb2 as video_dot_v1_dot_video__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amobile_video_service.proto\x12\x15mobileremote.video.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x10\x63ommon_rpc.proto\x1a\x1bvideo/v1/video_common.proto\"\x84\x01\n$OnConvoVideoStateChangedNotification\x12;\n\x11\x63onvo_video_state\x18\x01 \x01(\x0b\x32 .common.video.v1.ConvoVideoState\x12\x1f\n\x0fnotification_id\x18\x02 \x01(\tB\x06\xca\x9d%\x02\x30$2|\n\x0bMobileVideo\x12m\n\x18OnConvoVideoStateChanged\x12;.mobileremote.video.v1.OnConvoVideoStateChangedNotification\x1a\x14.common.VoidResponseBl\n\x1a\x63om.kik.video.mobileremoteZNgithub.com/kikinteractive/xiphias-api-mobileremote/generated/go/video/v1;videob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobile_video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.kik.video.mobileremoteZNgithub.com/kikinteractive/xiphias-api-mobileremote/generated/go/video/v1;video'
  _globals['_ONCONVOVIDEOSTATECHANGEDNOTIFICATION'].fields_by_name['notification_id']._loaded_options = None
  _globals['_ONCONVOVIDEOSTATECHANGEDNOTIFICATION'].fields_by_name['notification_id']._serialized_options = b'\312\235%\0020$'
  _globals['_ONCONVOVIDEOSTATECHANGEDNOTIFICATION']._serialized_start=148
  _globals['_ONCONVOVIDEOSTATECHANGEDNOTIFICATION']._serialized_end=280
  _globals['_MOBILEVIDEO']._serialized_start=282
  _globals['_MOBILEVIDEO']._serialized_end=406
# @@protoc_insertion_point(module_scope)
