# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: login/jwt/v1/mobile_jwt_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import kik_unofficial.protobuf.protobuf_validation_pb2
import kik_unofficial.protobuf.common_model_pb2
import kik_unofficial.protobuf.login.v1.mobile_login_service_pb2
import kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2


class MobileLoginJwtBase(abc.ABC):

    @abc.abstractmethod
    async def RefreshToken(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenRequest, kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/mobile.login.jwt.v1.MobileLoginJwt/RefreshToken': grpclib.const.Handler(
                self.RefreshToken,
                grpclib.const.Cardinality.UNARY_UNARY,
                kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenRequest,
                kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenResponse,
            ),
        }


class MobileLoginJwtStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.RefreshToken = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.login.jwt.v1.MobileLoginJwt/RefreshToken',
            kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenRequest,
            kik_unofficial.protobuf.login.jwt.v1.mobile_jwt_service_pb2.RefreshTokenResponse,
        )
