# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity/v1/subscription_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.entity.v1 import subscription_common_pb2 as entity_dot_v1_dot_subscription__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$entity/v1/subscription_service.proto\x12\x10mobile.entity.v1\x1a\x19protobuf_validation.proto\x1a#entity/v1/subscription_common.proto\"K\n\x17SyncMyRosterDataRequest\x12\x30\n\x05token\x18\x01 \x01(\x0b\x32!.common.entity.v1.RosterSyncToken\"\x8f\x02\n\x18SyncMyRosterDataResponse\x12\x41\n\x06result\x18\x01 \x01(\x0e\x32\x31.mobile.entity.v1.SyncMyRosterDataResponse.Result\x12<\n\x0broster_data\x18\x02 \x03(\x0b\x32\x1d.common.entity.v1.RosterEntryB\x08\xca\x9d%\x04\x80\x01\xf4\x03\x12\x30\n\x05token\x18\x03 \x01(\x0b\x32!.common.entity.v1.RosterSyncToken\x12\x10\n\x08has_more\x18\x04 \x01(\x08\".\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0bNOT_ALLOWED\x10\x01\x12\x0b\n\x07\x44\x45LAYED\x10\x02\x32y\n\x0cSubscription\x12i\n\x10SyncMyRosterData\x12).mobile.entity.v1.SyncMyRosterDataRequest\x1a*.mobile.entity.v1.SyncMyRosterDataResponseBp\n\"com.kik.entity.subscription.mobileZJgithub.com/kikinteractive/xiphias-api-mobile/generated/go/entity/v1;entityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity.v1.subscription_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.kik.entity.subscription.mobileZJgithub.com/kikinteractive/xiphias-api-mobile/generated/go/entity/v1;entity'
  _globals['_SYNCMYROSTERDATARESPONSE'].fields_by_name['roster_data']._loaded_options = None
  _globals['_SYNCMYROSTERDATARESPONSE'].fields_by_name['roster_data']._serialized_options = b'\312\235%\004\200\001\364\003'
  _globals['_SYNCMYROSTERDATAREQUEST']._serialized_start=122
  _globals['_SYNCMYROSTERDATAREQUEST']._serialized_end=197
  _globals['_SYNCMYROSTERDATARESPONSE']._serialized_start=200
  _globals['_SYNCMYROSTERDATARESPONSE']._serialized_end=471
  _globals['_SYNCMYROSTERDATARESPONSE_RESULT']._serialized_start=425
  _globals['_SYNCMYROSTERDATARESPONSE_RESULT']._serialized_end=471
  _globals['_SUBSCRIPTION']._serialized_start=473
  _globals['_SUBSCRIPTION']._serialized_end=594
# @@protoc_insertion_point(module_scope)
