# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antispam/appledevicecheck/v1/assertion_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3antispam/appledevicecheck/v1/assertion_common.proto\x12#common.antispam.appledevicecheck.v1\"J\n\x14\x43reateTopicAssertion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rbackground_id\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"\x98\x01\n\x1dProfilePictureUploadAssertion\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x18\n\x10\x62lockhash_scaled\x18\x03 \x01(\t\x12\x13\n\x0bsha1_scaled\x18\x04 \x01(\t\x12\x15\n\rsha1_original\x18\x05 \x01(\t\x12\r\n\x05nonce\x18\x06 \x01(\t\"V\n\x13JwtRefreshAssertion\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x0b\n\x03jti\x18\x03 \x01(\t\x12\r\n\x05nonce\x18\x04 \x01(\t\"^\n\x14\x43reateGroupAssertion\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\ngroup_name\x18\x03 \x01(\t\x12\r\n\x05nonce\x18\x04 \x01(\t*b\n\x0f\x41ssertionAction\x12\x0e\n\nTOPIC_POST\x10\x00\x12\x1a\n\x16PROFILE_PICTURE_UPLOAD\x10\x01\x12\x0f\n\x0bJWT_REFRESH\x10\x02\x12\x12\n\x0eGROUP_CREATION\x10\x03\x42\x94\x01\n\'com.kik.antispam.appledevicecheck.modelZigithub.com/kikinteractive/xiphias-model-common/generated/go/antispam/appledevicecheck/v1;appledevicecheckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antispam.appledevicecheck.v1.assertion_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.kik.antispam.appledevicecheck.modelZigithub.com/kikinteractive/xiphias-model-common/generated/go/antispam/appledevicecheck/v1;appledevicecheck'
  _globals['_ASSERTIONACTION']._serialized_start=507
  _globals['_ASSERTIONACTION']._serialized_end=605
  _globals['_CREATETOPICASSERTION']._serialized_start=92
  _globals['_CREATETOPICASSERTION']._serialized_end=166
  _globals['_PROFILEPICTUREUPLOADASSERTION']._serialized_start=169
  _globals['_PROFILEPICTUREUPLOADASSERTION']._serialized_end=321
  _globals['_JWTREFRESHASSERTION']._serialized_start=323
  _globals['_JWTREFRESHASSERTION']._serialized_end=409
  _globals['_CREATEGROUPASSERTION']._serialized_start=411
  _globals['_CREATEGROUPASSERTION']._serialized_end=505
# @@protoc_insertion_point(module_scope)
