# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: antispam/appledevicecheck/v1/mobile_apple_device_check_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import kik_unofficial.protobuf.protobuf_validation_pb2
import kik_unofficial.protobuf.antispam.appledevicecheck.v1.assertion_common_pb2
import kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2


class AppleDeviceCheckBase(abc.ABC):

    @abc.abstractmethod
    async def GetNonce(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceRequest, kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetAssertionNonce(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceRequest, kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def VerifyAttestationResult(self, stream: 'grpclib.server.Stream[kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultRequest, kik_unofficial.protobuf.antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/GetNonce': grpclib.const.Handler(
                self.GetNonce,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceRequest,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceResponse,
            ),
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/GetAssertionNonce': grpclib.const.Handler(
                self.GetAssertionNonce,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceRequest,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceResponse,
            ),
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/VerifyAttestationResult': grpclib.const.Handler(
                self.VerifyAttestationResult,
                grpclib.const.Cardinality.UNARY_UNARY,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultRequest,
kik_unofficial.protobuf.                antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultResponse,
            ),
        }


class AppleDeviceCheckStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetNonce = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/GetNonce',
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceRequest,
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetNonceResponse,
        )
        self.GetAssertionNonce = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/GetAssertionNonce',
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceRequest,
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.GetAssertionNonceResponse,
        )
        self.VerifyAttestationResult = grpclib.client.UnaryUnaryMethod(
            channel,
            '/mobile.antispam.appledevicecheck.v1.AppleDeviceCheck/VerifyAttestationResult',
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultRequest,
kik_unofficial.protobuf.            antispam.appledevicecheck.v1.mobile_apple_device_check_service_pb2.VerifyAttestationResultResponse,
        )
