# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persona/v2/persona_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n persona/v2/persona_service.proto\x12\x11mobile.persona.v2\x1a\x19protobuf_validation.proto\x1a\x15\x63ommon/v2/model.proto\"\xf4\x01\n\x15SetDisplayNameRequest\x12\x30\n\npersona_id\x18\x01 \x01(\x0b\x32\x14.common.v2.PersonaIdB\x06\xca\x9d%\x02\x08\x01\x12M\n\x0bperson_name\x18\x02 \x01(\x0b\x32\x36.mobile.persona.v2.SetDisplayNameRequest.FirstLastNameH\x00\x1aJ\n\rFirstLastName\x12\x1d\n\nfirst_name\x18\x01 \x01(\tB\t\xca\x9d%\x05\x08\x01 \xff\x01\x12\x1a\n\tlast_name\x18\x02 \x01(\tB\x07\xca\x9d%\x03 \xff\x01\x42\x0e\n\x0c\x64isplay_name\"\xbe\x01\n\x16SetDisplayNameResponse\x12@\n\x06result\x18\x01 \x01(\x0e\x32\x30.mobile.persona.v2.SetDisplayNameResponse.Result\"b\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x12\n\x0eNOT_MODIFIABLE\x10\x02\x12\x16\n\x12\x46IRST_NAME_INVALID\x10\x03\x12\x15\n\x11LAST_NAME_INVALID\x10\x04\x32r\n\x07Persona\x12g\n\x0eSetDisplayName\x12(.mobile.persona.v2.SetDisplayNameRequest\x1a).mobile.persona.v2.SetDisplayNameResponse\"\x00\x42{\n\x16\x63om.kik.gen.persona.v2ZLgithub.com/kikinteractive/xiphias-api-mobile/generated/go/persona/v2;persona\xa2\x02\x12KPBMobilePersonaV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persona.v2.persona_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.kik.gen.persona.v2ZLgithub.com/kikinteractive/xiphias-api-mobile/generated/go/persona/v2;persona\242\002\022KPBMobilePersonaV2'
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME'].fields_by_name['first_name']._loaded_options = None
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME'].fields_by_name['first_name']._serialized_options = b'\312\235%\005\010\001 \377\001'
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME'].fields_by_name['last_name']._loaded_options = None
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME'].fields_by_name['last_name']._serialized_options = b'\312\235%\003 \377\001'
  _globals['_SETDISPLAYNAMEREQUEST'].fields_by_name['persona_id']._loaded_options = None
  _globals['_SETDISPLAYNAMEREQUEST'].fields_by_name['persona_id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_SETDISPLAYNAMEREQUEST']._serialized_start=106
  _globals['_SETDISPLAYNAMEREQUEST']._serialized_end=350
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME']._serialized_start=260
  _globals['_SETDISPLAYNAMEREQUEST_FIRSTLASTNAME']._serialized_end=334
  _globals['_SETDISPLAYNAMERESPONSE']._serialized_start=353
  _globals['_SETDISPLAYNAMERESPONSE']._serialized_end=543
  _globals['_SETDISPLAYNAMERESPONSE_RESULT']._serialized_start=445
  _globals['_SETDISPLAYNAMERESPONSE_RESULT']._serialized_end=543
  _globals['_PERSONA']._serialized_start=545
  _globals['_PERSONA']._serialized_end=659
# @@protoc_insertion_point(module_scope)
