# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kin/authentication/v1/authentication_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
from kik_unofficial.protobuf.common.v1 import model_pb2 as common_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1kin/authentication/v1/authentication_common.proto\x12\x1c\x63ommon.kin.authentication.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x15\x63ommon/v1/model.proto\"_\n\x07OfferId\x12$\n\nproduct_id\x18\x01 \x01(\x0b\x32\x0e.common.XiUuidH\x00\x12%\n\x10\x66\x65\x61ture_offer_id\x18\x02 \x01(\tB\t\xca\x9d%\x05(\x01\x30\x80\x01H\x00\x42\x07\n\x05value\"l\n\x08OfferJwt\x12\x39\n\x02id\x18\x01 \x01(\x0b\x32%.common.kin.authentication.v1.OfferIdB\x06\xca\x9d%\x02\x08\x01\x12%\n\x03jwt\x18\x02 \x01(\x0b\x32\x10.common.v1.XiJWTB\x06\xca\x9d%\x02\x08\x01\x42\x84\x01\n com.kik.kin.authentication.modelZ`github.com/kikinteractive/xiphias-model-common/generated/go/kin/authentication/v1;authenticationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kin.authentication.v1.authentication_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.kik.kin.authentication.modelZ`github.com/kikinteractive/xiphias-model-common/generated/go/kin/authentication/v1;authentication'
  _globals['_OFFERID'].fields_by_name['feature_offer_id']._loaded_options = None
  _globals['_OFFERID'].fields_by_name['feature_offer_id']._serialized_options = b'\312\235%\005(\0010\200\001'
  _globals['_OFFERJWT'].fields_by_name['id']._loaded_options = None
  _globals['_OFFERJWT'].fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_OFFERJWT'].fields_by_name['jwt']._loaded_options = None
  _globals['_OFFERJWT'].fields_by_name['jwt']._serialized_options = b'\312\235%\002\010\001'
  _globals['_OFFERID']._serialized_start=153
  _globals['_OFFERID']._serialized_end=248
  _globals['_OFFERJWT']._serialized_start=250
  _globals['_OFFERJWT']._serialized_end=358
# @@protoc_insertion_point(module_scope)
