# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kin/authentication/v1/authentication_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
from kik_unofficial.protobuf.common.v1 import model_pb2 as common_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2kin/authentication/v1/authentication_service.proto\x12\x1cmobile.kin.authentication.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x15\x63ommon/v1/model.proto\"I\n\x16GenerateUserJwtRequest\x12/\n\x08user_jid\x18\x01 \x01(\x0b\x32\x15.common.XiBareUserJidB\x06\xca\x9d%\x02\x08\x01\"\xfb\x01\n\x17GenerateUserJwtResponse\x12L\n\x06result\x18\x01 \x01(\x0e\x32<.mobile.kin.authentication.v1.GenerateUserJwtResponse.Result\x12N\n\x10rejection_reason\x18\x02 \x01(\x0b\x32\x34.mobile.kin.authentication.v1.UserJwtRejectionReason\x12\"\n\x08user_jwt\x18\x03 \x01(\x0b\x32\x10.common.v1.XiJWT\"\x1e\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\"\x98\x01\n\x16UserJwtRejectionReason\x12G\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x39.mobile.kin.authentication.v1.UserJwtRejectionReason.Code\"5\n\x04\x43ode\x12\x0b\n\x07UNKNOWN\x10\x00\x12 \n\x1cREJECTED_USER_NOT_AUTHORIZED\x10\x01\x32\x90\x01\n\x0e\x41uthentication\x12~\n\x0fGenerateUserJwt\x12\x34.mobile.kin.authentication.v1.GenerateUserJwtRequest\x1a\x35.mobile.kin.authentication.v1.GenerateUserJwtResponseB\x80\x01\n\x1e\x63om.kik.kin.authentication.rpcZ^github.com/kikinteractive/xiphias-api-mobile/generated/go/kin/authentication/v1;authenticationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kin.authentication.v1.authentication_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.kik.kin.authentication.rpcZ^github.com/kikinteractive/xiphias-api-mobile/generated/go/kin/authentication/v1;authentication'
  _globals['_GENERATEUSERJWTREQUEST'].fields_by_name['user_jid']._loaded_options = None
  _globals['_GENERATEUSERJWTREQUEST'].fields_by_name['user_jid']._serialized_options = b'\312\235%\002\010\001'
  _globals['_GENERATEUSERJWTREQUEST']._serialized_start=154
  _globals['_GENERATEUSERJWTREQUEST']._serialized_end=227
  _globals['_GENERATEUSERJWTRESPONSE']._serialized_start=230
  _globals['_GENERATEUSERJWTRESPONSE']._serialized_end=481
  _globals['_GENERATEUSERJWTRESPONSE_RESULT']._serialized_start=451
  _globals['_GENERATEUSERJWTRESPONSE_RESULT']._serialized_end=481
  _globals['_USERJWTREJECTIONREASON']._serialized_start=484
  _globals['_USERJWTREJECTIONREASON']._serialized_end=636
  _globals['_USERJWTREJECTIONREASON_CODE']._serialized_start=583
  _globals['_USERJWTREJECTIONREASON_CODE']._serialized_end=636
  _globals['_AUTHENTICATION']._serialized_start=639
  _globals['_AUTHENTICATION']._serialized_end=783
# @@protoc_insertion_point(module_scope)
