# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product/v1/product_data_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.common.v1 import model_pb2 as common_dot_v1_dot_model__pb2
from kik_unofficial.protobuf.kin.authentication.v1 import authentication_common_pb2 as kin_dot_authentication_dot_v1_dot_authentication__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$product/v1/product_data_common.proto\x12\x11\x63ommon.product.v1\x1a\x19protobuf_validation.proto\x1a\x15\x63ommon/v1/model.proto\x1a\x31kin/authentication/v1/authentication_common.proto\"\x1e\n\tPriceData\x12\x11\n\tkin_value\x18\x01 \x01(\x04\"!\n\x0cPurchaseData\x12\x11\n\tpurchased\x18\x01 \x01(\x08\"}\n\x13PaymentConfirmation\x12?\n\x08offer_id\x18\x01 \x01(\x0b\x32%.common.kin.authentication.v1.OfferIdB\x06\xca\x9d%\x02\x08\x01\x12%\n\x03jwt\x18\x02 \x01(\x0b\x32\x10.common.v1.XiJWTB\x06\xca\x9d%\x02\x08\x01\x42g\n\x15\x63om.kik.product.modelZNgithub.com/kikinteractive/xiphias-model-common/generated/go/product/v1;productb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product.v1.product_data_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.kik.product.modelZNgithub.com/kikinteractive/xiphias-model-common/generated/go/product/v1;product'
  _globals['_PAYMENTCONFIRMATION'].fields_by_name['offer_id']._loaded_options = None
  _globals['_PAYMENTCONFIRMATION'].fields_by_name['offer_id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_PAYMENTCONFIRMATION'].fields_by_name['jwt']._loaded_options = None
  _globals['_PAYMENTCONFIRMATION'].fields_by_name['jwt']._serialized_options = b'\312\235%\002\010\001'
  _globals['_PRICEDATA']._serialized_start=160
  _globals['_PRICEDATA']._serialized_end=190
  _globals['_PURCHASEDATA']._serialized_start=192
  _globals['_PURCHASEDATA']._serialized_end=225
  _globals['_PAYMENTCONFIRMATION']._serialized_start=227
  _globals['_PAYMENTCONFIRMATION']._serialized_end=352
# @@protoc_insertion_point(module_scope)
