# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matching/v1/matching_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
from kik_unofficial.protobuf.common.v1 import model_pb2 as common_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!matching/v1/matching_common.proto\x12\x12\x63ommon.matching.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x15\x63ommon/v1/model.proto\"\x86\x01\n\x16\x41nonMatchingSessionKey\x12$\n\nsession_id\x18\x01 \x01(\x0b\x32\x0e.common.XiUuidH\x00\x12\x33\n\x12\x63hat_partner_alias\x18\x02 \x01(\x0b\x32\x15.common.v1.XiAliasJidH\x00\x42\x11\n\x0f\x63hat_session_id*0\n\x10\x43hatSessionState\x12\x0f\n\x0b\x43HAT_ACTIVE\x10\x00\x12\x0b\n\x07\x45XPIRED\x10\x02\x42s\n\x16\x63om.kik.matching.modelZPgithub.com/kikinteractive/xiphias-model-common/generated/go/matching/v1;matching\xa0\x01\x01\xa2\x02\x03MATb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching.v1.matching_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.kik.matching.modelZPgithub.com/kikinteractive/xiphias-model-common/generated/go/matching/v1;matching\240\001\001\242\002\003MAT'
  _globals['_CHATSESSIONSTATE']._serialized_start=264
  _globals['_CHATSESSIONSTATE']._serialized_end=312
  _globals['_ANONMATCHINGSESSIONKEY']._serialized_start=128
  _globals['_ANONMATCHINGSESSIONKEY']._serialized_end=262
# @@protoc_insertion_point(module_scope)
