# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridgetest/v1/preregistration_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.common_rpc_pb2 as common__rpc__pb2
from kik_unofficial.protobuf.bridgetest.v1 import bridgetest_common_pb2 as bridgetest_dot_v1_dot_bridgetest__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+bridgetest/v1/preregistration_service.proto\x12\x14mobile.bridgetest.v1\x1a\x10\x63ommon_rpc.proto\x1a%bridgetest/v1/bridgetest_common.proto2\xcf\x02\n\x0fPreRegistration\x12M\n\x04\x45\x63ho\x12!.common.bridgetest.v1.EchoRequest\x1a\".common.bridgetest.v1.EchoResponse\x12\x45\n\x07Workout\x12$.common.bridgetest.v1.WorkoutRequest\x1a\x14.common.VoidResponse\x12\x36\n\tException\x12\x13.common.VoidRequest\x1a\x14.common.VoidResponse\x12n\n\x0fValidateHeaders\x12,.common.bridgetest.v1.ValidateHeadersRequest\x1a-.common.bridgetest.v1.ValidateHeadersResponseBh\n\x12\x63om.kik.bridgetestZRgithub.com/kikinteractive/xiphias-api-mobile/generated/go/bridgetest/v1;bridgetestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridgetest.v1.preregistration_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.kik.bridgetestZRgithub.com/kikinteractive/xiphias-api-mobile/generated/go/bridgetest/v1;bridgetest'
  _globals['_PREREGISTRATION']._serialized_start=127
  _globals['_PREREGISTRATION']._serialized_end=462
# @@protoc_insertion_point(module_scope)
