# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups/v2/groups_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgroups/v2/groups_common.proto\x12\x10\x63ommon.groups.v2\x1a\x19protobuf_validation.proto\"G\n\x11PublicGroupFields\x12\x32\n\x07hashtag\x18\x01 \x01(\x0b\x32\x19.common.groups.v2.HashtagB\x06\xca\x9d%\x02\x08\x01\"3\n\x07Hashtag\x12(\n\x07hashtag\x18\x01 \x01(\tB\x17\xca\x9d%\x13\x08\x01\x12\x0f^#[\\w\\.]{2,32}$By\n\x15\x63om.kik.gen.groups.v2ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/groups/v2;groups\xa2\x02\x11KPBCommonGroupsV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups.v2.groups_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.kik.gen.groups.v2ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/groups/v2;groups\242\002\021KPBCommonGroupsV2'
  _globals['_PUBLICGROUPFIELDS'].fields_by_name['hashtag']._loaded_options = None
  _globals['_PUBLICGROUPFIELDS'].fields_by_name['hashtag']._serialized_options = b'\312\235%\002\010\001'
  _globals['_HASHTAG'].fields_by_name['hashtag']._loaded_options = None
  _globals['_HASHTAG'].fields_by_name['hashtag']._serialized_options = b'\312\235%\023\010\001\022\017^#[\\w\\.]{2,32}$'
  _globals['_PUBLICGROUPFIELDS']._serialized_start=78
  _globals['_PUBLICGROUPFIELDS']._serialized_end=149
  _globals['_HASHTAG']._serialized_start=151
  _globals['_HASHTAG']._serialized_end=202
# @@protoc_insertion_point(module_scope)
