# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chats/v2/chats_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63hats/v2/chats_common.proto\x12\x0f\x63ommon.chats.v2\x1a\x15\x63ommon/v2/model.proto\x1a\x19protobuf_validation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0b\x43hatThemeId\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x0f.common.v2.UuidB\x06\xca\x9d%\x02\x08\x01\"\x90\x01\n\nMuteStatus\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".common.chats.v2.MuteStatus.Status\x12*\n\x06\x65xpiry\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x06Status\x12\r\n\tNOT_MUTED\x10\x00\x12\t\n\x05MUTED\x10\x01\x42u\n\x14\x63om.kik.gen.chats.v2ZJgithub.com/kikinteractive/xiphias-model-common/generated/go/chats/v2;chats\xa2\x02\x10KPBCommonChatsV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chats.v2.chats_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.kik.gen.chats.v2ZJgithub.com/kikinteractive/xiphias-model-common/generated/go/chats/v2;chats\242\002\020KPBCommonChatsV2'
  _globals['_CHATTHEMEID'].fields_by_name['id']._loaded_options = None
  _globals['_CHATTHEMEID'].fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_CHATTHEMEID']._serialized_start=131
  _globals['_CHATTHEMEID']._serialized_end=181
  _globals['_MUTESTATUS']._serialized_start=184
  _globals['_MUTESTATUS']._serialized_end=328
  _globals['_MUTESTATUS_STATUS']._serialized_start=294
  _globals['_MUTESTATUS_STATUS']._serialized_end=328
# @@protoc_insertion_point(module_scope)
