# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iam/v2/authentication_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2
from kik_unofficial.protobuf.session.v2 import model_pb2 as session_dot_v2_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#iam/v2/authentication_service.proto\x12\rmobile.iam.v2\x1a\x19protobuf_validation.proto\x1a\x15\x63ommon/v2/model.proto\x1a\x16session/v2/model.proto\"\xca\x03\n\x13\x41uthenticateRequest\x12V\n\x14username_credentials\x18\x01 \x01(\x0b\x32\x36.mobile.iam.v2.AuthenticateRequest.UsernameCredentialsH\x00\x12P\n\x11\x65mail_credentials\x18\x02 \x01(\x0b\x32\x33.mobile.iam.v2.AuthenticateRequest.EmailCredentialsH\x00\x12?\n\x12\x63lient_instance_id\x18\n \x01(\x0b\x32\x1b.common.v2.ClientInstanceIdB\x06\xca\x9d%\x02\x08\x01\x1a`\n\x13UsernameCredentials\x12-\n\x08username\x18\x01 \x01(\x0b\x32\x13.common.v2.UsernameB\x06\xca\x9d%\x02\x08\x01\x12\x1a\n\x07passkey\x18\x02 \x01(\x0c\x42\t\xca\x9d%\x05\x08\x01\x30\x80\x08\x1aW\n\x10\x45mailCredentials\x12\'\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x10.common.v2.EmailB\x06\xca\x9d%\x02\x08\x01\x12\x1a\n\x07passkey\x18\x02 \x01(\x0c\x42\t\xca\x9d%\x05\x08\x01\x30\x80\x08\x42\r\n\x0b\x63redentials\"\x81\x02\n\x14\x41uthenticateResponse\x12:\n\x06result\x18\x01 \x01(\x0e\x32*.mobile.iam.v2.AuthenticateResponse.Result\x12\x36\n\rsession_token\x18\x02 \x01(\x0b\x32\x1f.common.session.v2.SessionToken\x12(\n\naccount_id\x18\x03 \x01(\x0b\x32\x14.common.v2.AccountId\x12-\n\x0fgenesis_persona\x18\x04 \x01(\x0b\x32\x14.common.v2.PersonaId\"\x1c\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"\x0f\n\rLogoutRequest\"X\n\x0eLogoutResponse\x12\x34\n\x06result\x18\x01 \x01(\x0e\x32$.mobile.iam.v2.LogoutResponse.Result\"\x10\n\x06Result\x12\x06\n\x02OK\x10\x00\x32\xb4\x01\n\x0e\x41uthentication\x12Y\n\x0c\x41uthenticate\x12\".mobile.iam.v2.AuthenticateRequest\x1a#.mobile.iam.v2.AuthenticateResponse\"\x00\x12G\n\x06Logout\x12\x1c.mobile.iam.v2.LogoutRequest\x1a\x1d.mobile.iam.v2.LogoutResponse\"\x00\x42k\n\x12\x63om.kik.gen.iam.v2ZDgithub.com/kikinteractive/xiphias-api-mobile/generated/go/iam/v2;iam\xa2\x02\x0eKPBMobileIAMV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iam.v2.authentication_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.kik.gen.iam.v2ZDgithub.com/kikinteractive/xiphias-api-mobile/generated/go/iam/v2;iam\242\002\016KPBMobileIAMV2'
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS'].fields_by_name['username']._loaded_options = None
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS'].fields_by_name['username']._serialized_options = b'\312\235%\002\010\001'
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS'].fields_by_name['passkey']._loaded_options = None
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS'].fields_by_name['passkey']._serialized_options = b'\312\235%\005\010\0010\200\010'
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS'].fields_by_name['email']._loaded_options = None
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS'].fields_by_name['email']._serialized_options = b'\312\235%\002\010\001'
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS'].fields_by_name['passkey']._loaded_options = None
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS'].fields_by_name['passkey']._serialized_options = b'\312\235%\005\010\0010\200\010'
  _globals['_AUTHENTICATEREQUEST'].fields_by_name['client_instance_id']._loaded_options = None
  _globals['_AUTHENTICATEREQUEST'].fields_by_name['client_instance_id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_AUTHENTICATEREQUEST']._serialized_start=129
  _globals['_AUTHENTICATEREQUEST']._serialized_end=587
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS']._serialized_start=387
  _globals['_AUTHENTICATEREQUEST_USERNAMECREDENTIALS']._serialized_end=483
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS']._serialized_start=485
  _globals['_AUTHENTICATEREQUEST_EMAILCREDENTIALS']._serialized_end=572
  _globals['_AUTHENTICATERESPONSE']._serialized_start=590
  _globals['_AUTHENTICATERESPONSE']._serialized_end=847
  _globals['_AUTHENTICATERESPONSE_RESULT']._serialized_start=819
  _globals['_AUTHENTICATERESPONSE_RESULT']._serialized_end=847
  _globals['_LOGOUTREQUEST']._serialized_start=849
  _globals['_LOGOUTREQUEST']._serialized_end=864
  _globals['_LOGOUTRESPONSE']._serialized_start=866
  _globals['_LOGOUTRESPONSE']._serialized_end=954
  _globals['_LOGOUTRESPONSE_RESULT']._serialized_start=819
  _globals['_LOGOUTRESPONSE_RESULT']._serialized_end=835
  _globals['_AUTHENTICATION']._serialized_start=957
  _globals['_AUTHENTICATION']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
