# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal/v2/model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15signal/v2/model.proto\x12\x10\x63ommon.signal.v2\x1a\x19protobuf_validation.proto\x1a\x15\x63ommon/v2/model.proto\"\xda\x01\n\x06Signal\x12/\n\x02id\x18\x01 \x01(\x0b\x32\x1b.common.signal.v2.Signal.IdB\x06\xca\x9d%\x02\x08\x01\x12\x37\n\rglobal_signal\x18\x02 \x01(\x0b\x32\x1e.common.signal.v2.GlobalSignalH\x00\x12\x39\n\x0epersona_signal\x18\x03 \x01(\x0b\x32\x1f.common.signal.v2.PersonaSignalH\x00\x1a#\n\x02Id\x12\x1d\n\traw_value\x18\x01 \x01(\x0c\x42\n\xca\x9d%\x06\x08\x01(\x10\x30 B\x06\n\x04kind\"\x0e\n\x0cGlobalSignal\"A\n\rPersonaSignal\x12\x30\n\npersona_id\x18\x01 \x01(\x0b\x32\x14.common.v2.PersonaIdB\x06\xca\x9d%\x02\x08\x00\x42y\n\x15\x63om.kik.gen.signal.v2ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/signal/v2;signal\xa2\x02\x11KPBCommonSignalV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal.v2.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.kik.gen.signal.v2ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/signal/v2;signal\242\002\021KPBCommonSignalV2'
  _globals['_SIGNAL_ID'].fields_by_name['raw_value']._loaded_options = None
  _globals['_SIGNAL_ID'].fields_by_name['raw_value']._serialized_options = b'\312\235%\006\010\001(\0200 '
  _globals['_SIGNAL'].fields_by_name['id']._loaded_options = None
  _globals['_SIGNAL'].fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_PERSONASIGNAL'].fields_by_name['persona_id']._loaded_options = None
  _globals['_PERSONASIGNAL'].fields_by_name['persona_id']._serialized_options = b'\312\235%\002\010\000'
  _globals['_SIGNAL']._serialized_start=94
  _globals['_SIGNAL']._serialized_end=312
  _globals['_SIGNAL_ID']._serialized_start=269
  _globals['_SIGNAL_ID']._serialized_end=304
  _globals['_GLOBALSIGNAL']._serialized_start=314
  _globals['_GLOBALSIGNAL']._serialized_end=328
  _globals['_PERSONASIGNAL']._serialized_start=330
  _globals['_PERSONASIGNAL']._serialized_end=395
# @@protoc_insertion_point(module_scope)
