# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/v2/client_meta.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.kik_options_pb2 as kik__options__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63lient/v2/client_meta.proto\x12\x10\x63ommon.client.v2\x1a\x11kik_options.proto\x1a\x19protobuf_validation.proto\x1a\x15\x63ommon/v2/model.proto\"\xb6\x01\n\rDeviceDetails\x12?\n\x0b\x64\x65vice_type\x18\x01 \x01(\x0e\x32*.common.client.v2.DeviceDetails.DeviceType\x12\x36\n\tclient_id\x18\x02 \x01(\x0b\x32\x1b.common.v2.ClientInstanceIdB\x06\xca\x9d%\x02\x08\x01\",\n\nDeviceType\x12\x0b\n\x07\x41NDROID\x10\x00\x12\x07\n\x03IOS\x10\x01\x12\x08\n\x04TEST\x10\x02\"\xa5\x01\n\rClientVersion\x12%\n\x05major\x18\x01 \x01(\rB\x16\xca\x9d%\x12\x39\x01\x00\x00\x00\x00\x00\x00\x00\x41\x00\x00\x00\x80\x00\x00\x00\x00\x12\x1c\n\x05minor\x18\x02 \x01(\rB\r\xca\x9d%\tA\x00\x00\x00\x80\x00\x00\x00\x00\x12\x1d\n\x06\x62ugfix\x18\x03 \x01(\rB\r\xca\x9d%\tA\x00\x00\x00\x80\x00\x00\x00\x00\x12\x15\n\x05\x62uild\x18\x04 \x01(\tB\x06\xca\x9d%\x02\x30\n\x12\x19\n\tdev_build\x18\x05 \x01(\tB\x06\xca\x9d%\x02\x30\n\"Q\n\x0c\x43lientLocale\x12\x41\n\x06locale\x18\x01 \x01(\tB1\xca\x9d%-\x12+^(?i)[a-z]{2,8}(?:_([a-z]{2}|[0-9]{2,3}))?$B\x9e\x01\n\x1c\x63om.kik.gen.common.client.v2B\x10\x43lientModelProtoP\x01ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/client/v2;client\xa0\x01\x01\xa2\x02\x12KPBCCommonClientV2\xaa\xa3*\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.v2.client_meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.kik.gen.common.client.v2B\020ClientModelProtoP\001ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/client/v2;client\240\001\001\242\002\022KPBCCommonClientV2\252\243*\002\010\001'
  _globals['_DEVICEDETAILS'].fields_by_name['client_id']._loaded_options = None
  _globals['_DEVICEDETAILS'].fields_by_name['client_id']._serialized_options = b'\312\235%\002\010\001'
  _globals['_CLIENTVERSION'].fields_by_name['major']._loaded_options = None
  _globals['_CLIENTVERSION'].fields_by_name['major']._serialized_options = b'\312\235%\0229\001\000\000\000\000\000\000\000A\000\000\000\200\000\000\000\000'
  _globals['_CLIENTVERSION'].fields_by_name['minor']._loaded_options = None
  _globals['_CLIENTVERSION'].fields_by_name['minor']._serialized_options = b'\312\235%\tA\000\000\000\200\000\000\000\000'
  _globals['_CLIENTVERSION'].fields_by_name['bugfix']._loaded_options = None
  _globals['_CLIENTVERSION'].fields_by_name['bugfix']._serialized_options = b'\312\235%\tA\000\000\000\200\000\000\000\000'
  _globals['_CLIENTVERSION'].fields_by_name['build']._loaded_options = None
  _globals['_CLIENTVERSION'].fields_by_name['build']._serialized_options = b'\312\235%\0020\n'
  _globals['_CLIENTVERSION'].fields_by_name['dev_build']._loaded_options = None
  _globals['_CLIENTVERSION'].fields_by_name['dev_build']._serialized_options = b'\312\235%\0020\n'
  _globals['_CLIENTLOCALE'].fields_by_name['locale']._loaded_options = None
  _globals['_CLIENTLOCALE'].fields_by_name['locale']._serialized_options = b'\312\235%-\022+^(?i)[a-z]{2,8}(?:_([a-z]{2}|[0-9]{2,3}))?$'
  _globals['_DEVICEDETAILS']._serialized_start=119
  _globals['_DEVICEDETAILS']._serialized_end=301
  _globals['_DEVICEDETAILS_DEVICETYPE']._serialized_start=257
  _globals['_DEVICEDETAILS_DEVICETYPE']._serialized_end=301
  _globals['_CLIENTVERSION']._serialized_start=304
  _globals['_CLIENTVERSION']._serialized_end=469
  _globals['_CLIENTLOCALE']._serialized_start=471
  _globals['_CLIENTLOCALE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
