# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antispam/safetynet/v1/safetynet_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.common_rpc_pb2 as common__rpc__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-antispam/safetynet/v1/safetynet_service.proto\x12\x1cmobile.antispam.safetynet.v1\x1a\x10\x63ommon_rpc.proto\x1a\x19protobuf_validation.proto\"\x84\x01\n\x10GetNonceResponse\x12\x45\n\x06result\x18\x01 \x01(\x0e\x32\x35.mobile.antispam.safetynet.v1.GetNonceResponse.Result\x12\x17\n\x05nonce\x18\x02 \x01(\tB\x08\xca\x9d%\x04\x08\x01(\x10\"\x10\n\x06Result\x12\x06\n\x02OK\x10\x00\";\n\x1eVerifyAttestationResultRequest\x12\x19\n\x03jws\x18\x01 \x01(\tB\x0c\xca\x9d%\x08\x08\x01(\x01\x30\xa8\xc3\x01\"\xb3\x01\n\x1fVerifyAttestationResultResponse\x12T\n\x06result\x18\x01 \x01(\x0e\x32\x44.mobile.antispam.safetynet.v1.VerifyAttestationResultResponse.Result\":\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_NONCE\x10\x01\x12\x15\n\x11MALFORMED_REQUEST\x10\x02\x32\xf9\x01\n\tSafetyNet\x12Q\n\x08GetNonce\x12\x13.common.VoidRequest\x1a..mobile.antispam.safetynet.v1.GetNonceResponse\"\x00\x12\x98\x01\n\x17VerifyAttestationResult\x12<.mobile.antispam.safetynet.v1.VerifyAttestationResultRequest\x1a=.mobile.antispam.safetynet.v1.VerifyAttestationResultResponse\"\x00\x42{\n\x1e\x63om.kik.antispam.safetynet.rpcZYgithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/safetynet/v1;safetynetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antispam.safetynet.v1.safetynet_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.kik.antispam.safetynet.rpcZYgithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/safetynet/v1;safetynet'
  _globals['_GETNONCERESPONSE'].fields_by_name['nonce']._loaded_options = None
  _globals['_GETNONCERESPONSE'].fields_by_name['nonce']._serialized_options = b'\312\235%\004\010\001(\020'
  _globals['_VERIFYATTESTATIONRESULTREQUEST'].fields_by_name['jws']._loaded_options = None
  _globals['_VERIFYATTESTATIONRESULTREQUEST'].fields_by_name['jws']._serialized_options = b'\312\235%\010\010\001(\0010\250\303\001'
  _globals['_GETNONCERESPONSE']._serialized_start=125
  _globals['_GETNONCERESPONSE']._serialized_end=257
  _globals['_GETNONCERESPONSE_RESULT']._serialized_start=241
  _globals['_GETNONCERESPONSE_RESULT']._serialized_end=257
  _globals['_VERIFYATTESTATIONRESULTREQUEST']._serialized_start=259
  _globals['_VERIFYATTESTATIONRESULTREQUEST']._serialized_end=318
  _globals['_VERIFYATTESTATIONRESULTRESPONSE']._serialized_start=321
  _globals['_VERIFYATTESTATIONRESULTRESPONSE']._serialized_end=500
  _globals['_VERIFYATTESTATIONRESULTRESPONSE_RESULT']._serialized_start=442
  _globals['_VERIFYATTESTATIONRESULTRESPONSE_RESULT']._serialized_end=500
  _globals['_SAFETYNET']._serialized_start=503
  _globals['_SAFETYNET']._serialized_end=752
# @@protoc_insertion_point(module_scope)
